# Step 1 : Import Required libraries

In [1]:
import pandas as pd
import numpy as np

# Step 2: Load datasets

In [2]:
X_train = pd.read_csv("../Dataset/X_train.csv")
X_test = pd.read_csv("../Dataset/X_test.csv")

y_train = pd.read_csv("../Dataset/y_train.csv").squeeze()
y_test = pd.read_csv("../Dataset/y_test.csv").squeeze()

X_train_scaled = pd.read_csv("../Dataset/X_train_scaled.csv")
X_test_scaled = pd.read_csv("../Dataset/X_test_scaled.csv")

# Step 3 : Linear Regression

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
lr_model = LinearRegression()

lr_model.fit(X_train_scaled, y_train)
y_pred_lr = lr_model.predict(X_test_scaled)

## Step 3.1 : Import Metrics

In [5]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Step 3.2 : Evaluate

In [6]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

## Result

In [7]:
print("MAE :", mae_lr)
print("RMSE :", rmse_lr)
print("R2 Score :", r2_lr)

MAE : 26.465153864807682
RMSE : 55.81999278684777
R2 Score : 0.7353526410152951

# Step 4 : Decision Tree

### Decision Tree Regression can capture non-linear relationships between features and the target variable and does not require feature scaling.

In [8]:
from sklearn.tree import DecisionTreeRegressor

In [9]:
dt_model = DecisionTreeRegressor(random_state=42)

dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

## Step 4.1 : Evaluate Model

In [10]:
mae_dt = mean_absolute_error(y_test, y_pred_dt)
rmse_dt = np.sqrt( mean_squared_error(y_test, y_pred_dt))
r2_dt = r2_score(y_test, y_pred_dt)

## Result

In [11]:
print("MAE :", mae_dt)
print("RMSE :", rmse_dt)
print("R2 Score :", r2_dt)

MAE : 25.23142771275279
RMSE : 66.44183285174948
R2 Score : 0.6250518450012474

## Observation

### Linear Regression achieved an R² score of 0.735 and outperformed Decision Tree Regression, which achieved an R² score of 0.611. Therefore, Linear Regression was selected as the better model among the two at this stage.

# Step 5 : Random Forest Regression

In [12]:
from sklearn.ensemble import RandomForestRegressor

In [13]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42  )

- n_estimators=100 → 100 decision trees will be created.
- random_state=42 → Ensures reproducible results.

In [14]:
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

## Evaluate Model

In [15]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

## Results

In [16]:
print("MAE :", mae_rf)
print("RMSE :", rmse_rf)
print("R2 Score :", r2_rf)

MAE : 21.210769770770796
RMSE : 52.369125397783606
R2 Score : 0.7670629054545479

# Step 6 : Report Observation

### Random Forest Regression achieved the best performance with an R² score of 0.767, outperforming Linear Regression and Decision Tree Regression. Therefore, Random Forest was selected as the final machine learning model for deployment.

## Step 6.1 : Comparison Table

In [17]:
results = pd.DataFrame({
    "Model": ["Linear Regression","Decision Tree","Random Forest" ],

    "MAE": [mae_lr,mae_dt, mae_rf],

    "RMSE": [rmse_lr,rmse_dt,rmse_rf ],

    "R2 Score": [r2_lr,r2_dt,r2_rf]
})
results

               Model        MAE       RMSE  R2 Score
0  Linear Regression  26.465154  55.819993  0.735353
1      Decision Tree  25.231428  66.441833  0.625052
2      Random Forest  21.210770  52.369125  0.767063

## Sort by Best Model

In [18]:
results.sort_values(by="R2 Score",ascending=False)

               Model        MAE       RMSE  R2 Score
2      Random Forest  21.210770  52.369125  0.767063
0  Linear Regression  26.465154  55.819993  0.735353
1      Decision Tree  25.231428  66.441833  0.625052

- Random Forest achieved the highest R² score.
- Random Forest also achieved the lowest MAE and RMSE.
- Therefore, Random Forest was selected as the best machine learning model.

# Step 7 : Save Best ML Model

In [19]:
import pickle

pickle.dump( rf_model,open("../Models/best_ml_model.pkl", "wb"))